# Generated by Django 3.1.7 on 2021-03-21 07:55

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassVersion',
            fields=[
                ('version', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'class_version',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='WeightVersion',
            fields=[
                ('version', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('class_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slqe.classversion')),
            ],
            options={
                'db_table': 'weight_version',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('uid', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slqe.role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('expression', models.CharField(max_length=255)),
                ('latex', models.CharField(max_length=255)),
                ('roots', django_mysql.models.ListCharField(models.CharField(max_length=255), max_length=2560, size=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slqe.user')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
