# Generated by Django 3.1.7 on 2021-03-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slqe', '0004_auto_20210323_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='success',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
