# Generated by Django 3.1.7 on 2021-03-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slqe', '0006_auto_20210323_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
