# Generated by Django 3.1.7 on 2021-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slqe', '0007_auto_20210323_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
