# Generated by Django 3.1.7 on 2021-04-25 06:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slqe', '0008_auto_20210330_1456'),
    ]

    operations = [





        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=2550)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_read', models.BooleanField(default=False)),
                ('url', models.CharField(default=None, max_length=255)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('loss_function_path', models.CharField(default='', max_length=255)),
                ('log_path', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slqe.user')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
