# Generated by Django 3.1.7 on 2021-03-31 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slqe', '0008_auto_20210330_1456'),
    ]
    operations = [
        migrations.AlterField(
            model_name='weightversion',
            name='class_version',
            field=models.ForeignKey(db_constraint=False, on_delete=models.deletion.CASCADE, to='classversion')
        ),
        migrations.AlterField(
            model_name='classversion',
            name='version',
            field=models.CharField(blank=True, max_length=255, db_index=False),
        ),
        migrations.AddField(
            model_name='classversion',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weightversion',
            name='version',
            field=models.CharField(max_length=255, db_index=False),
        ),
        migrations.AddField(
            model_name='weightversion',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weightversion',
            name='class_version',
            field=models.ForeignKey(db_constraint=True, on_delete=models.deletion.CASCADE, to='classversion')
        ),
        migrations.RemoveField(
            model_name='classversion',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='weightversion',
            name='date_time',
        ),
        migrations.AddField(
            model_name='classversion',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),

        migrations.AddField(
            model_name='weightversion',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='weightversion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
