# Generated by Django 3.1.7 on 2021-04-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slqe', '0009_auto_20210401_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classversion',
            name='version',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='weightversion',
            name='version',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
