# Generated by Django 3.1.7 on 2021-04-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slqe', '0009_notification'),
        ('slqe', '0011_auto_20210401_1736'),
    ]

    operations = [
    ]
