# Generated by Django 3.1.7 on 2021-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slqe', '0012_merge_20210407_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
