# Generated by Django 3.1.7 on 2021-04-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slqe', '0013_auto_20210407_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='classversion',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
