# Generated by Django 3.1.7 on 2021-04-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slqe', '0014_auto_20210411_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='log_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='loss_function_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='weightversion',
            name='log_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='weightversion',
            name='loss_function_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
